# Configuration

# Main
experiment_name: 'normal'

create_patches:
  patch_size: 256
  step_size: 256

feature_extraction:
  model_name: uni_v1
  batch_size: 512
  slide_ext: .svs


model_configuration:
  batch_size: 1
  hidden_size: 128
  epochs: 100
  test_size: 0.1
  k_folds: 4
  n_heads: 8
  learning_rate: 0.001
  attention_class: AttentionMIL