# Configuration

data_path: "./mil_wsi/data/"
results_path: "./mil_wsi/results/"
metrics_path: "./mil_wsi/metrics/"
models_path: "./mil_wsi/models/"

# Main
experiment_name: 'bracs'

create_patches:
  patch_size: 256
  step_size: 256

feature_extraction:
  model_name: uni_v1
  batch_size: 512
  slide_ext: .svs


model_configuration:
  batch_size: 1
  hidden_size: 128
  epochs: 2
  test_size: 0.16
  k_folds: 4
  n_heads: 1
  learning_rate: 0.001
  attention_class: AttentionMIL